# Training config file
# Contains paths and hyperparameters 

description: "Training configs for Digit-sum RNN"

model:
  model_type: rnn
  hidden_size: 128

train:
  dataset_path: null
  n_epochs: 100
  learning_rate: 1e-3
  train_split_fraction: 0.8
  batch_size: 32
  log_path: logs
  run_name: null
  weight_decay: null

test:
  dataset_path: null
  model_path: null
  sequence: null

# --- Hydra settings ---
# Disable Hydra logging, you can leave these as default

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
