[project]
name = "rnn-101"
version = "0.1.0"
description = "An introduction to Recurrent Neural Networks"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flake8>=7.1.1",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "torch>=2.5.1",
]
